training:
  seed: 63
  batch_size: 64
  epochs: 100
  lr: 0.0001
  eta_min: 0.00001
  weight_decay: 0.001

model:
  type: 'resnext'
  layer: 101
  version: 1
  trainable: true
  trainable_layers: -1

data:
  data_dir: 'data/'

testing:
  enable_tta: true
  params_pth: './params/resnext101v1_b64_e100_lr0.0001_sd63.pt'
