training:
  seed: 63
  batch_size: 32
  epochs: 100
  lr: 0.0001
  eta_min: 0.00001
  weight_decay: 0.001

model:
  type: 'resnext'
  layer: 50
  version: 0
  trainable: true
  trainable_layers: -1

data:
  data_dir: 'data/'

testing:
  params_pth: './params/resnext50v0_b16_e5_lr0.0001_sd63.pt'